# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2010-2019, Intel Corporation. All rights reserved.
# Makefile - Ryan's homework 3 led blink read/write 82583v device Linux driver
#
obj-$(CONFIG_VENDOR_RYAN) += homework2.o

